//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 03:55:46 PM EDT 
//


package com.hpccsystems.salt.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "concept-fields", propOrder = {
    "conceptFieldname",
    "nonNull"
})
public class ConceptFieldDef {

    @XmlElement(required = true)
    protected String conceptFieldname;
    @XmlElement(required = true)
    protected String nonNull;
	
	public String getConceptFieldname() {
		return conceptFieldname;
	}
	public void setConceptFieldname(String conceptFieldname) {
		this.conceptFieldname = conceptFieldname;
	}
	public String getNonNull() {

		return nonNull;
	}
	public void setNonNull(String nonNull) {
		this.nonNull = nonNull;
	}


}
