//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 03:55:46 PM EDT 
//


package com.hpccsystems.salt.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/*
 * conceptName;
    private String effectOnSpecificity;
    private String threshold;
    private boolean useBagOfWords;
    private String reOrderType;
    private String segmentType;
    private String scale;
    private String specificity;
    private String switchValue;
    private ArrayList fields
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "concept-def", propOrder = {
    "conceptName",
    "effectOnSpecificity",
    "threshold",
    "useBagOfWords",
    "reOrderType",
    "segmentType",
    "scale",
    "specificity",
    "switchValue",
    "conceptfields"
})
public class ConceptDef {

    @XmlElement(required = true)
    protected String conceptName;
    @XmlElement(required = false)
    protected String effectOnSpecificity;
    
    @XmlElement(required = false)
    protected String threshold;
    
    @XmlElement(required = false)
    protected String useBagOfWords;
    
    @XmlElement(required = false)
    protected String reOrderType;
    
    @XmlElement(required = false)
    protected String segmentType;
    
    @XmlElement(required = false)
    protected String scale;
    
    @XmlElement(required = false)
    protected String specificity;
    
    @XmlElement(required = false)
    protected String switchValue;
    
    @XmlElement(required = true)
    protected ConceptDef.ConceptFields conceptFields;

	public String getConceptName() {
		return conceptName;
	}

	public void setConceptName(String conceptName) {
		this.conceptName = conceptName;
	}

	public String getEffectOnSpecificity() {
		return effectOnSpecificity;
	}

	public void setEffectOnSpecificity(String effectOnSpecificity) {
		this.effectOnSpecificity = effectOnSpecificity;
	}

	public String getThreshold() {
		return threshold;
	}

	public void setThreshold(String threshold) {
		this.threshold = threshold;
	}

	public String getUseBagOfWords() {
		return useBagOfWords;
	}

	public void setUseBagOfWords(String useBagOfWords) {
		this.useBagOfWords = useBagOfWords;
	}

	public String getReOrderType() {
		return reOrderType;
	}

	public void setReOrderType(String reOrderType) {
		this.reOrderType = reOrderType;
	}

	public String getSegmentType() {
		return segmentType;
	}

	public void setSegmentType(String segmentType) {
		this.segmentType = segmentType;
	}

	public String getScale() {
		return scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getSpecificity() {
		return specificity;
	}

	public void setSpecificity(String specificity) {
		this.specificity = specificity;
	}

	public String getSwitchValue() {
		return switchValue;
	}

	public void setSwitchValue(String switchValue) {
		this.switchValue = switchValue;
	}

	public ConceptDef.ConceptFields getConceptFields() {
		return conceptFields;
	}

	public void setConceptFields(ConceptDef.ConceptFields conceptFields) {
		this.conceptFields = conceptFields;
	}

	 
	 
	public static class ConceptFields {

	        protected List<ConceptFieldDef> conceptFieldDef;

	        public List<ConceptFieldDef> getConceptFieldDef() {
	            if (conceptFieldDef == null) {
	            	conceptFieldDef = new ArrayList<ConceptFieldDef>();
	            }
	            return this.conceptFieldDef;
	        }

	    }

}
