//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 03:55:46 PM EDT 
//


package com.hpccsystems.salt.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hygiene-rule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hygiene-rule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caps" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lefttrim" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="righttrim" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="allow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="onfail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="field-specificity> type="string" maxOccurs="1" minOccurs="0" />
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hygiene-rule", propOrder = {
    "name",
    "caps",
    "lefttrim",
    "righttrim",
    "allow",
    "spaces",
    "onfail",
    "field-specificity"
})
public class HygieneRule {

    @XmlElement(required = true)
    protected String name;
    protected Boolean caps;
    protected Boolean lefttrim;
    protected Boolean righttrim;
    protected String allow;
    protected String spaces;
    protected String onfail;
    protected String fieldspecificity = "0";

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the caps property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCaps() {
        return caps;
    }

    /**
     * Sets the value of the caps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCaps(Boolean value) {
        this.caps = value;
    }

    /**
     * Gets the value of the lefttrim property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLefttrim() {
        return lefttrim;
    }

    /**
     * Sets the value of the lefttrim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLefttrim(Boolean value) {
        this.lefttrim = value;
    }

    /**
     * Gets the value of the righttrim property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRighttrim() {
        return righttrim;
    }

    /**
     * Sets the value of the righttrim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRighttrim(Boolean value) {
        this.righttrim = value;
    }

    /**
     * Gets the value of the allow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllow() {
        return allow;
    }

    /**
     * Sets the value of the allow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllow(String value) {
        this.allow = value;
    }

    /**
     * Gets the value of the spaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpaces() {
        return spaces;
    }

    /**
     * Sets the value of the spaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpaces(String value) {
        this.spaces = value;
    }

    /**
     * Gets the value of the onfail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnfail() {
        return onfail;
    }

    /**
     * Sets the value of the onfail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnfail(String value) {
        this.onfail = value;
    }

	public String getFieldspecificity() {
		if(fieldspecificity == null){
			fieldspecificity = "0";
		}
		return fieldspecificity;
	}

	public void setFieldspecificity(String fieldspecificity) {
		if(fieldspecificity == null){
			fieldspecificity = "0";
		}
		this.fieldspecificity = fieldspecificity;
	}
    
    

}
